#!/bin/bash

if [ $# -ne 6 ]; then
    echo "Usage: submit_job <PROCESS_GRID_SIZE> <MPI_TASKS> <INV_GRID_SIZE_1D> <MAX_ITR> <ERROR_LIMIT> <LOG_FILE_NAME>"
    exit 1
fi

GRID_SIZE=$1
MPI_TASKS=$2
INV_GRID_SIZE_1D=$3
MAX_ITR=$4
ERROR_LIMIT=$5
FNAME=$6
: "${CODE_HOME:?Env variable CODE_HOME must be set to point to the repository root}"
echo $CODE_HOME
NNODES=`python -c "from math import ceil; print int(ceil($MPI_TASKS))"`

sed -e "s/\${GRID_SIZE}/${GRID_SIZE}/" Makefile.template > Makefile

make

sed -e "s/\${MPI_TASKS}/${MPI_TASKS}/" \
    -e "s/\${CODE_HOME}/${CODE_HOME//\//\\/}/" \
    -e "s/\${INV_GRID_SIZE_1D}/${INV_GRID_SIZE_1D}/" \
    -e "s/\${MAX_ITR}/${MAX_ITR}/" \
    -e "s/\${ERROR_LIMIT}/${ERROR_LIMIT}/" \
    -e "s/\${NNODES}/${NNODES}/" \
    -e "s/\${FNAME}/${FNAME}/" sbatch.template > sbatch.final

## Run using sbatch
#sbatch sbatch.final
mpiexec -n ${MPI_TASKS} ./cg ${INV_GRID_SIZE_1D} ${MAX_ITR} ${ERROR_LIMIT}

